version: '3'
services:
  web:
    image: prestashop/prestashop:1.7-7.2-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mariadb:10.3.2
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    ports:
      - 3306:3306
