<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container27t7grv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container27t7grv/appProdProjectContainer.php') {
    touch(__DIR__.'/Container27t7grv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container27t7grv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container27t7grv\appProdProjectContainer([
    'container.build_hash' => '27t7grv',
    'container.build_id' => '57d5648f',
    'container.build_time' => 1570375752,
], __DIR__.\DIRECTORY_SEPARATOR.'Container27t7grv');
