<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxd7aog\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxd7aog/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSxd7aog.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSxd7aog\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSxd7aog\appProdProjectContainer([
    'container.build_hash' => 'Sxd7aog',
    'container.build_id' => '8ba554bc',
    'container.build_time' => 1570379669,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxd7aog');
